version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: books_cat_database
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - postgres.env
    ports:
      - 5432:5432

volumes:
  postgres-data:
